@echo off
rem ============================================================
rem One-time DURABLE build of the ALL-SECTOR catalyst-feed MVP.
rem Registered as Windows Task Scheduler task "Catalyst MVP Build",
rem fires once ~10:02 PM Central 2026-07-23. Survives Claude session exit.
rem Log: reports\catalyst_build.log
rem ============================================================
setlocal
set REPO=C:\Users\osuby\tradingview-mcp
set LOG=%REPO%\reports\catalyst_build.log
cd /d "%REPO%"
echo. >> "%LOG%"
echo ===== Catalyst MVP build START %date% %time% ===== >> "%LOG%"
claude -p "Build the ALL-SECTOR catalyst-feed MVP per research/catalyst-feed-scope.md (covers every sector, not just biopharma). FIRST verify the real current Central time via https://timeapi.io/api/time/current/zone?timeZone=America/Chicago (the sandbox `date` clock has been unreliable - do not trust it). Then build the FREE MVP with two layers: (A) EARNINGS layer, ALL SECTORS - pull the TradingView scanner (scanner.tradingview.com/america/scan) with columns earnings_release_next_date, earnings_per_share_forecast_next_fq, sector, close, market_cap_basic; filter type=stock, exchange in NYSE/NASDAQ/AMEX, cap>~300M, price>5; keep names whose next earnings date is within the next 7 days -> the cross-sector earnings calendar; where possible add a SUE overlay via the existing scripts/edgar_sue_backtest.py machinery. (B) BIOPHARMA BINARY layer - ClinicalTrials.gov API v2 Phase 2/3 INDUSTRY trials with primary completion in the next ~9 months, mapped to tickers via SEC company_tickers.json + a small alias table (public US only). Then: (1) write research/catalyst-calendar.json (one record per event: ticker, company, sector, event_type, date_or_window, detail, est_eps_or_SUE, source, and a short plain-English VIEW on how it may play out - SUE/PEAD-informed for earnings, BINARY-labeled for biopharma). (2) INTEGRATE INTO THE DAILY WORKBOOK (columns on tickers, NOT just a standalone tab): in scripts/compile_universe_report_v2.py JOIN the calendar onto the per-ticker tabs (Fresh Buys, Plans, Blocked, Sell Mode, Market Movers, etc.) by ticker, adding TWO columns to each row - 'Catalyst' (event type + date, e.g. 'Earnings 7/28' or 'PDUFA ~8/15') and 'Catalyst View' (what it is + how it may play out + ALWAYS a SUGGESTED ACTION per the trading-execution-protocol: e.g. trim into / do NOT hold full size through / spec-size sized for total loss / defined-risk options / post-confirmation entry / awareness-only; the action must fit the event type - earnings use the SUE/PEAD lens, biopharma = binary defined-risk, other = context, and say 'awareness-only, no edge' where we genuinely have none rather than inventing a call); leave blank where the ticker has no near catalyst; give both columns tooltips per the scan_workbook_style standard. (3) ALSO keep a COMPACT list of catalyst names that are NOT in the scanned universe, so blind-spot names (e.g. CRNX) still surface. (4) Wire a DAILY REFRESH: add a step to scripts/run_eod_chain.bat that rebuilds research/catalyst-calendar.json BEFORE the compile step, so the columns are fresh every day. (5) Flag convergence with ignition/origination; add a one-line catalyst note to the brief. Test end-to-end, commit to branch add-watchlist-files, and try PushNotification to tell Omar it is done or blocked. Work fully autonomously; never wait for input." >> "%LOG%" 2>&1
echo ===== Catalyst MVP build DONE %date% %time% (exit %errorlevel%) ===== >> "%LOG%"
endlocal
